### PR TITLE
ci: add calling workflow for add-to-project.yml

### PR DESCRIPTION
**Pull request by koeaw**
Add new calling workflow for local reusable add-to-project workflow so issues opened in this very repo are also added to the Prosnet project.

### CODE REVIEW

**Comment by koeaw** [comment]
TIL
> cannot specify version when calling local workflows

**Review by b1rger — CHANGES_REQUESTED** [review]
Given that this only affects this repository and has no effect to downstream projects, this should not be a `feat` but a `ci` or `chore`. If its a feat, it will lead to a bump in the version

**Comment by koeaw** [comment]
> Given that this only affects this repository and has no effect to downstream projects, this should not be a `feat` but a `ci` or `chore`. If its a feat, it will lead to a bump in the version

Changed the type to `ci`, thx for the reminder re: version bump.

**Review by b1rger — APPROVED** [review]

**Comment by koeaw** [comment]
(+ renamed PR title for consistency/later findability)

**Pull request merged**
